import os 
import sys 
import numpy as np 
import pandas as pd 
import dill 
from src.exception import CustomException

def save_object(object, file_path):
    pass 
